# Usa una imagen de PHP 8.1 con Apache como base
FROM php:8.2-apache

# Instala los paquetes necesarios y limpia la caché de APT
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    libonig-dev \
    zlib1g-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    && rm -rf /var/lib/apt/lists/*

# Configura ServerName para Apache
RUN echo 'ServerName localhost' >> /etc/apache2/apache2.conf

# Instala y configura las extensiones que Laravel necesita
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

# Configura el directorio raíz de Apache a la carpeta public de Laravel
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
    && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Copia el código fuente de tu aplicación Laravel al contenedor
COPY . /var/www/html

# Otorga permisos al directorio de almacenamiento de Laravel
RUN chown -R www-data:www-data /var/www/html/storage \
    && chmod -R 775 /var/www/html/storage

# Instala Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Instala las dependencias de Laravel
RUN composer install --no-interaction --no-plugins --no-scripts --prefer-dist

# Instala Laravel Passport
RUN composer require laravel/passport

# Exponer el puerto 8080
EXPOSE 8000

# Comandos para iniciar Apache
CMD ["apache2-foreground"]

# Instala netcat para el script de inicio
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

# Copia el script de inicio al contenedor
COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

# Configura el script de inicio como el punto de entrada
ENTRYPOINT ["start.sh"]
